buildscript {
    repositories {
        mavenCentral()
        google()
    }
}

plugins {
    id 'com.android.application' version '8.4.0'
    id 'org.jetbrains.kotlin.android' version '1.9.20'
}

android {
    namespace 'eu.kanade.tachiyomi.extension.en.ishallmasterthisfamily'
    compileSdk 34
    
    defaultConfig {
        applicationId 'eu.kanade.tachiyomi.extension.en.ishallmasterthisfamily'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    // THIS IS THE FIX: Explicitly point Android to your custom Mihon folder paths
    sourceSets {
        main {
            manifest.srcFile 'manifest-fix/AndroidManifest.xml'
            java.srcDirs = ['src/en/ishallmasterthisfamily/src']
            res.srcDirs = ['src/en/ishallmasterthisfamily/res']
            assets.srcDirs = ['src/en/ishallmasterthisfamily/assets']
        }
    }
}

dependencies {
    implementation "org.jsoup:jsoup:1.16.1"
    implementation "com.squareup.okhttp3:okhttp:4.11.0"
}