name: Remote Extension Builder

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Compile Extension APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v4

    - name: Set up Java Environment
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate Gradle Wrapper Files
      run: gradle wrapper --gradle-version 8.9

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew

    - name: Build Extension Package with Gradle
      run: ./gradlew assembleRelease --no-daemon

    - name: Upload Finished APK File
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Mihon-Extension
        path: "**/build/outputs/apk/release/*.apk"